services:
  dev-container:
    working_dir: /app
    environment:
      COMPOSER_NO_DEV: "0"
    build:
      context: .
      dockerfile: php-cli.Dockerfile
    container_name: dev-container
    image: multidialogo-php-legal-form-guesser:latest
    volumes:
      - ./..:/app
