services:
  dev-container:
    working_dir: /app
    environment:
      COMPOSER_NO_DEV: "0"
    build:
      context: .
      dockerfile: php74-composer.Dockerfile
    container_name: dev-container
    image: multidialogo-php-legal-form-guesser-composer:latest
    volumes:
      - ./..:/app
